# Prometheus configuration for Sochi Travel
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'sochi-travel'
    environment: 'production'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (if deployed)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # API Backend
  - job_name: 'sochi-travel-api'
    static_configs:
      - targets: ['api:4000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # MariaDB Exporter (if deployed)
  - job_name: 'mariadb'
    static_configs:
      - targets: ['mariadb-exporter:9104']

  # Redis Exporter (if deployed)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Nginx Exporter (if deployed)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  # MinIO (built-in metrics)
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    metrics_path: '/minio/v2/metrics/cluster'

